runtime: python
entrypoint: gunicorn -b :$PORT cysuite.wsgi
env: flex

includes:
  - env_variables.yaml
  
handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto

beta_settings:
  cloud_sql_instances: cysuite:us-central1:cysuite-db

runtime_config:
  python_version: 3.7

resources:
  cpu: 2
  memory_gb: 2.3
  disk_size_gb: 10
  volumes:
  - name: ramdisk1
    volume_type: tmpfs
    size_gb: 0.5

readiness_check:
  path: "/readiness_check"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

liveness_check:
  path: "/liveness_check"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.6
  target_concurrent_requests: 100