version: "3.8"

services:
  django:
    build: .
    container_name: django
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    command: >
      sh -c "python3 manage.py makemigrations cyauth &&
             python3 manage.py makemigrations main &&
             python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - pgdb
      - redis

  pgdb:
    image: postgres:10-alpine
    container_name: pgdb
    env_file:
      - ./.env.dev
    volumes: 
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:alpine
  celery:
    restart: always
    build: .
    command: celery -A cysuite worker -P threads -l INFO --concurrency=8
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env.dev
    depends_on:
      - pgdb
      - redis
      - django
volumes:
  pgdata: