version: "3.9"

services:
  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: django
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  db:
    image: postgres:10-alpine
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes: 
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: redis:alpine
  celery:
    restart: always
    build: .
    command: celery -A cysuite worker -P threads -l INFO --concurrency=8
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - django
volumes:
  db_data: