# Generated by Django 3.2.6 on 2021-08-15 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='id',
            new_name='user_id',
        ),
    ]
