# Generated by Django 3.2.5 on 2021-10-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.TextField(default='default.jpeg', max_length=250, unique=True),
        ),
    ]
