# Generated by Django 3.2.5 on 2021-08-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
