# Generated by Django 3.2.5 on 2021-07-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='feedback',
            field=models.CharField(default='', max_length=1200),
        ),
    ]
