# Generated by Django 3.2.9 on 2022-02-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='repo_project_chosen',
            field=models.BooleanField(default=False),
        ),
    ]
