# Generated by Django 3.2.6 on 2021-08-15 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyauth', '0002_rename_id_account_user_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='people',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='profile',
        ),
    ]
