# Generated by Django 3.2.9 on 2022-01-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyauth', '0002_account_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='company',
            field=models.CharField(blank=True, default='N/A', max_length=128),
        ),
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(blank=True, default='N/A', max_length=64),
        ),
    ]
