# Generated by Django 3.2.8 on 2021-10-16 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyauth', '0002_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.TextField(default='default.jpeg', max_length=250),
        ),
    ]
