# Generated by Django 3.2.6 on 2021-08-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyauth', '0002_account_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='fname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='lname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
