# Generated by Django 3.2.9 on 2022-01-11 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyauth', '0003_auto_20220111_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='occupation',
        ),
    ]
