# Generated by Django 3.2.9 on 2022-01-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyauth', '0004_remove_account_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_repo_linked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='social_provider',
            field=models.CharField(default='N/A', max_length=64),
        ),
    ]
