# Generated by Django 3.2.6 on 2021-08-09 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyauth', '0004_auto_20210807_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='lname',
            new_name='last_name',
        ),
    ]
