# Generated by Django 3.2.6 on 2021-08-09 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyauth', '0005_auto_20210809_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='first_name',
            new_name='family_name',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='last_name',
            new_name='given_name',
        ),
    ]
