# Generated by Django 3.2.5 on 2021-07-31 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_code', models.TextField()),
                ('amount', models.IntegerField()),
                ('first_payment_date', models.DateTimeField(auto_now=True)),
                ('latest_payment_date', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.transaction')),
            ],
        ),
    ]
