# Generated by Django 3.2.6 on 2021-08-17 16:24

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cyauth', '0003_auto_20210815_1948'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayloadModel',
            fields=[
                ('payload_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='payload', serialize=False, to='cyauth.account')),
                ('payload_image', models.ImageField(blank=True, default='default.png', null=True, upload_to='payloads/')),
            ],
            options={
                'verbose_name': 'payload',
                'verbose_name_plural': 'payloads',
                'db_table': 'payload',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_account', models.TextField(default='None', max_length=30)),
                ('given_name', models.TextField(blank=True, max_length=50, null=True)),
                ('last_name', models.TextField(blank=True, max_length=50, null=True)),
                ('payer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('currency', models.TextField(blank=True, max_length=10, null=True)),
                ('status', models.TextField(blank=True, max_length=254, null=True)),
                ('transaction_code', models.TextField(blank=True, max_length=50, null=True, unique=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='WordlistModel',
            fields=[
                ('wordlist_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wordlist', serialize=False, to='cyauth.account')),
                ('wordlist_file_1', models.FileField(blank=True, default='media/rockyou.txt', null=True, upload_to='')),
                ('wordlist_file_2', models.FileField(blank=True, default='media/all.txt', null=True, upload_to='')),
                ('wordlist_file_3', models.FileField(blank=True, default=None, null=True, upload_to='wordlists/')),
            ],
            options={
                'verbose_name': 'wordlist',
                'verbose_name_plural': 'wordlists',
                'db_table': 'wordlist',
            },
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=30, unique=True)),
                ('program', models.TextField(max_length=30)),
                ('in_scope_domains', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250), default=list, size=None)),
                ('progress', models.IntegerField(default=100)),
                ('subdomains', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250), default=list, size=None)),
                ('project_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'db_table': 'project',
                'ordering': ('project_user', 'project_name', 'program', 'in_scope_domains', 'progress', 'subdomains'),
            },
        ),
    ]
