# Generated by Django 3.2.6 on 2021-08-26 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyauth', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTaskModel',
            fields=[
                ('task_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='celerytask', serialize=False, to='cyauth.account')),
                ('subdomain_task', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
