# Generated by Django 3.2.5 on 2021-08-31 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomainmodel',
            name='header_info',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
