# Generated by Django 3.2.6 on 2021-08-22 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subdomainmodel',
            table='subdomain',
        ),
    ]
