# Generated by Django 3.2.5 on 2021-10-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomainmodel',
            name='screenshot',
            field=models.ImageField(blank=True, default='screenshots/no_screenshot.png', null=True, upload_to='screenshots/'),
        ),
    ]
