# Generated by Django 3.2.6 on 2021-08-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordlistmodel',
            name='wordlist_file_1',
            field=models.FileField(default='media/rockyou.txt', editable='False', upload_to=''),
        ),
        migrations.AlterField(
            model_name='wordlistmodel',
            name='wordlist_file_2',
            field=models.FileField(default='media/all.txt', editable='False', upload_to=''),
        ),
    ]
