# Generated by Django 3.2.6 on 2021-08-15 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_payloadmodel_payload_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='payloadmodel',
            table='payload',
        ),
    ]
