# Generated by Django 3.2.6 on 2021-08-26 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_celerytaskmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celerytaskmodel',
            name='subdomain_task',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
