# Generated by Django 3.2.6 on 2021-08-17 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210817_1626'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='wordlistmodel',
            table='wordlists',
        ),
    ]
