# Generated by Django 3.2.5 on 2021-07-31 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210731_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='given_name',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
