# Generated by Django 3.2.5 on 2021-10-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_subdomainmodel_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomainmodel',
            name='screenshot',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
