# Generated by Django 3.2.6 on 2021-08-15 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_payloadmodel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transaction',
            table='payments',
        ),
    ]
