# Generated by Django 3.2.6 on 2021-08-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_wordlistmodel_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordlistmodel',
            name='wordlist_file_4',
            field=models.FileField(blank=True, default=None, null=True, upload_to='wordlists/'),
        ),
        migrations.AddField(
            model_name='wordlistmodel',
            name='wordlist_file_5',
            field=models.FileField(blank=True, default=None, null=True, upload_to='wordlists/'),
        ),
        migrations.AlterModelTable(
            name='wordlistmodel',
            table='wordlist',
        ),
    ]
