# Generated by Django 3.2.6 on 2021-08-26 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_celerytaskmodel_subdomain_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='celerytaskmodel',
            options={'verbose_name': 'celerytask', 'verbose_name_plural': 'celerytask'},
        ),
        migrations.AlterModelTable(
            name='celerytaskmodel',
            table='celerytask',
        ),
    ]
