# Generated by Django 3.2.6 on 2021-08-29 19:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210826_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomainmodel',
            name='ports',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), blank=True, default=list, null=True, size=None),
        ),
    ]
