# Generated by Django 3.2.6 on 2021-08-10 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_alter_projectmodel_project_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmodel',
            options={'ordering': ('project_user', 'project_name', 'program', 'in_scope_domains'), 'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='project_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
