# Generated by Django 3.2.6 on 2021-08-18 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210817_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'periodical', 'verbose_name_plural': 'periodicals'},
        ),
        migrations.AlterModelTable(
            name='newsletter',
            table='periodical',
        ),
    ]
