# Generated by Django 3.2.6 on 2021-08-14 12:26

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_auto_20210810_1913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmodel',
            options={'ordering': ('project_user', 'project_name', 'program', 'in_scope_domains', 'progress', 'subdomains'), 'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='progress',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='subdomains',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250), default=list, size=None),
        ),
        migrations.CreateModel(
            name='PayloadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='payloads/')),
                ('payload_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payloads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'payload',
                'verbose_name_plural': 'payloads',
                'db_table': 'payloads',
            },
        ),
    ]
