# Generated by Django 3.2.6 on 2021-08-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210818_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='subscriber',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
