# Generated by Django 3.2.6 on 2021-08-14 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_auto_20210814_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payloadmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='payloadmodel',
            name='payload_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='payloads', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
