# Generated by Django 3.2.5 on 2021-07-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210731_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='first_payment_date',
            new_name='payment_date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='latest_payment_date',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user_account',
            field=models.TextField(default='None', max_length=30),
        ),
    ]
